language: node_js
node_js: 8
cache:
  cargo: true
  yarn: true

before_install:
  - export PATH="$HOME/.cargo/bin:$PATH"
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - cargo install cargo-web
  - cargo install --git https://github.com/alexcrichton/wasm-gc
  - cargo install --git https://github.com/alexcrichton/wasm-bindgen

script:
  - yarn test
  - for example in simple advanced-stdweb advanced-wasm-bindgen; do (cd examples/$example; yarn; yarn build); done
