language: node_js
node_js: 8
cache:
  cargo: true
  yarn: true

before_install:
  - export PATH="$HOME/.cargo/bin:$PATH"
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - rustup toolchain install nightly
  - rustup default nightly
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - cargo install cargo-web
  - cargo install --git https://github.com/alexcrichton/wasm-gc
